[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  function! LightLineFugitive()
    try
      if expand('%:t') !~? 'Tagbar\|Gundo\|NERD' && &ft !~? 'vimfiler' && exists('*fugitive#head')
        let mark = ''  " edit here for cool mark
        let branch = fugitive#head()
        return branch !=# '' ? mark.branch : ''
      endif
    catch
    endtry
    return ''
  endfunction
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=100
'''

[[plugins]]
repo = 'xuyuanp/nerdtree-git-plugin'
on_cmd = 'NERDTreeToggle'