[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-t> :NERDTreeToggle<CR>
'''

# colorscheme
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    syntax enable
    set background=dark
    colorscheme hybrid
'''

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set noshowmode
    let g:lightline = {
    \ 'colorscheme': 'wombat'
    \ }
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

### fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    nnoremap <silent><C-p> :History<CR>
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
    let g:neoterm_default_mod='belowright'
    let g:neoterm_size=10
    let g:neoterm_autoscroll=1
    tnoremap <silent> <C-w> <C-\><C-n><C-w>
    nnoremap <silent><C-t><C-t> :Ttoggle<CR>
'''

# snippets
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
    let g:UltiSnipsExpandTrigger='<c-j>'
    let g:UltiSnipsJumpForwardTrigger="<c-b>"
    let g:UltiSnipsJumpBackwardTrigger="<c-z>"
'''
[[plugins]]
repo = 'honza/vim-snippets'
