[[plugins]]
repo = 'mbbill/undotree'
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    nmap s <Plug>(easymotion-overwin-f2)
'''
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    vnoremap ? :'<,'>TComment<CR>
'''
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''